apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo-app-0402"
  description: "demo app"
  annotations:
    github.com/project-slug: leemills83/demo-app-0402
    backstage.io/techdocs-ref: url:https://github.com/leemills83/demo-app-0402
spec:
  type: website
  lifecycle: experimental
  owner: "leemills83"
